services:
  autorole-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloumechat-autorole-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
